spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/student
      username: postgres
      password: Tomas14061
      driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql

logging:
  level:
    org.springframework.web: DEBUG  # Spring MVC Logging
    org.springframework.security: DEBUG  # Spring Security Logging
    org.apache.catalina: DEBUG  # Tomcat Logging (if using Tomcat)